 extends:
   - 'airbnb-base'
 env:
   node: true
   browser: true
   jquery: true
 plugins:
   - eslint-plugin-html
 rules:
   semi: 0
   no-underscore-dangle: 0
   no-console: 0
   strict: 0
   func-names: 0
   consistent-return: 0
